runtime: python310
entrypoint: streamlit run app.py  # Ensure 'app.py' is your main file name

env_variables:
  GOOGLE_API_KEY: "AIzaSyD2RefERwH70vP4yIHnRDUzf61a_7uc9Rg"
  OTHER_VAR: "your-other-variable"

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.65

resources:
  cpu: 1
  memory_gb: 1

handlers:
  - url: /.*
    script: auto  # Automatically maps to your script

env: standard  # Use 'standard' environment